<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="NetVips" />
    <PackageReference Include="NetVips.Native" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NguyenBinh.Application\NguyenBinh.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NguyenBinh.IntegrationTests" />
    <InternalsVisibleTo Include="NguyenBinh.UnitTests" />
  </ItemGroup>
</Project>
